spring:
    datasource:
            url: jdbc:oracle:thin:@d32dbfl003.oera-t.local:1521/sendsoknad_q1
            username: ${DATASOURCE_USERNAME}
            password: ${DATASOURCE_PASSWORD}
            type: oracle.ucp.jdbc.PoolDataSource
            oracleucp:
                min-pool-size: 5
                max-pool-size: 15
soknad:
    alderspensjon:
        url: ${ALDERSPENSJON_LINK}
    brukerprofil:
        url: ${SOKNAD_BRUKERPROFIL_LINK}
    ettersending:
        antalldager: ${ETTERSENDING_ANTALL_DAGER}
    reelarbeidsoker:
        url: ${REELARBEIDSOKER_LINK}
    skjemaveileder:
        url: ${SKJEMAVEILEDER_LINK}
    webservice:
        henvendelse:
            sendsoknadservice:
                url: ${HENVENDELSE_SENDSOKNAD_URL}
        arena:
            sakogaktivitet:
                url: ${SAKOGAKTIVITETWS_URL}
            maalgruppe:
                url: ${MAALGRUPPEWS_URL}
saksoversikt:
    link:
        url: ${SAKSOVERSIKT_LINK}
dialogarena:
    navnolink:
        url: ${NAVNO_LINK}
    cms:
        url: ${DIALOGARENA_CMS_URL}
dittnav:
    link:
        url: ${DITTNAV_LINK}
no.nav:
       modig:
           security:
               sts:
                  url: ${SECURITY_TOKEN_SERVICE_URL}