spring:
    datasource:
       oracle:
            url: ${DATASOURCE_URL}
            username: ${DATASOURCE_USERNAME}
            password: ${DATASOURCE_PASSWORD}
            driver-class-name: oracle.jdbc.OracleDriver