spring:
    datasource:
       oracle:
            url: ${DATASOURCE_URL}
            username: ${ORACLE_USERNAME}
            password: ${ORACLE_PASSWORD}
            driver-class-name: oracle.jdbc.OracleDriver