server:
    servlet:
        context-path: ${SERVLET_CONTEXT_PATH}
management:
    endpoints:
        enabled-by-default: false
        web:
            base-path: /internal
            exposure:
                include: prometheus
            path-mapping:
                prometheus: metrics
    endpoint:
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true
spring:
    datasource:
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD}
        type: oracle.ucp.jdbc.PoolDataSource
        oracleucp:
            min-pool-size: 5
            max-pool-size: 30
    cache:
        ehcache:
            config: ehcache.xml
api-key:
    legacy-sts: ${LEGACY_STS_API_KEY}
    soknad-fss-proxy: ${SOKNAD_FSS_PROXY_API_KEY}
dialogarena:
    navnolink:
        url: ${NAVNO_LINK}
    cms:
        url: ${DIALOGARENA_CMS_URL}
dittnav:
    link:
        url: ${DITTNAV_LINK}
dineutbetalinger:
    link:
        url: ${DINE_UTBETALINGER_LINK}
dokumentinnsending:
    smtpServer:
        host: ${SMTP_SERVER_HOST}
        port: ${SMTP_SERVER_PORT}
kravdialoginformasjon:
    bilstonad.path: /soknadbilstonad/app
    soknadrefusjondagligreise.path: /soknadrefusjondagligreise/app
    soknadtilleggsstonader.path: /soknadtilleggsstonader/app
    tiltakspenger.path: /soknadtiltakspenger/app
    soknad.aap.gjenopptak.path: /soknadaap/app
    soknad.aap.fortsett.path: /soknadaap/app
    soknad.aap.ordinaer.path: /soknadaap/app
no.nav:
    modig:
        security:
            sts:
                rest:
                    url: ${SECURITY_TOKEN_SERVICE_REST_URL}
                    systemSamlPath: /rest/v1/sts/samltoken
                    exchangePath: /rest/v1/sts/token/exchange
soknad:
    alderspensjon:
        url: ${ALDERSPENSJON_LINK}
    brukerprofil:
        url: ${SOKNAD_BRUKERPROFIL_LINK}
    ettersending:
        antalldager: ${ETTERSENDING_ANTALL_DAGER}
    reelarbeidsoker:
        url: ${REELARBEIDSOKER_LINK}
    skjemaveileder:
        url: ${SKJEMAVEILEDER_LINK}
    webservice:
        arbeid:
            arbeidsforhold:
                url: ${ARBEIDSFORHOLD_SERVICE_URL}
            organisasjon:
                url: ${ORGANISASJON_SERVICE_URL}
        arena:
            maalgruppe:
                url: ${MAALGRUPPEWS_URL}
            personinfo:
                url: ${PERSONINFO_SERVICE_URL}
            sakogaktivitet:
                url: ${SAKOGAKTIVITETWS_URL}
        brukerprofil:
            brukerprofilservice:
                url: ${BRUKER_PROFIL_SERVICE_URL}
        person:
            personservice:
                url: ${PERSON_SERVICE_URL}
soknadinnsending:
    url: ${SOKNADINNSENDING_URL}
    soknad:
        path: /soknadinnsending/soknad
soknadtilleggsstonader:
    path: /soknadtilleggsstonader/app
saksoversikt:
    link:
        url: ${SAKSOVERSIKT_LINK}
sendsoknad:
    datadir: ${SEND_SOKNAD_DATADIR}
    rest:
        kodeverk:
            url: ${KODEVERK_REST_URL}
    webservice:
        kodeverk:
            url: ${KODEVERK_SERVICE_URL}
systemuser:
    sendsoknad:
        username: ${SERVICEUSER_USERNAME}
        password: ${SERVICEUSER_PASSWORD}
    personInfo:
        username: ${PERSONINFORMASJON_USERNAME}
        password: ${PERSONINFORMASJON_PASSWORD}
innsending:
    soknadsfillager:
        host: ${SOKNADSFILLAGER_HOST}
        username: ${INNSENDING_USERNAME}
        password: ${INNSENDING_PASSWORD}
    soknadsmottaker:
        host: ${SOKNADSMOTTAKER_HOST}
        username: ${INNSENDING_USERNAME}
        password: ${INNSENDING_PASSWORD}
    brukernotifikasjon:
        tjensteUrl: ${BRUKERNOTIFIKASJON_TJENSTE_URL}
        username: ${INNSENDING_USERNAME}
        password: ${INNSENDING_PASSWORD}
kafka:
    applicationId: ${KAFKA_STREAMS_APPLICATION_ID}
    brokers: ${KAFKA_BROKERS}
    security:
        enabled: ${KAFKA_SECURITY}
        protocol: SSL
        keyStoreType: PKCS12
        keyStorePath: ${KAFKA_KEYSTORE_PATH}
        keyStorePassword: ${KAFKA_CREDSTORE_PASSWORD}
        trustStorePath: ${KAFKA_TRUSTSTORE_PATH}
        trustStorePassword: ${KAFKA_CREDSTORE_PASSWORD}
    topics:
        messageTopic: ${KAFKA_MESSAGE_TOPIC}

no.nav.security.jwt:
    issuers: tokenx
    issuer.tokenx:
        discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
        #https://soknad-oauth2-mock.dev.nav.no/default/.well-known/openid-configuration
        accepted_audience: ${ACCEPTED_AUDIENCE}
    client.registration:
        soknad-fss-proxy-azuread:
            token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            grant-type: client_credentials
            scope: ${SOKNAD_FSS_PROXY_SCOPE}
            authentication:
                client-id: ${AZURE_APP_CLIENT_ID}
                client-secret: ${AZURE_APP_CLIENT_SECRET}
                client-auth-method: client_secret_basic
        soknadsmottaker:
            token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            grant-type: client_credentials
            scope: ${SOKNADSMOTTAKER_SCOPE}
            authentication:
                client-id: ${AZURE_APP_CLIENT_ID}
                client-secret: ${AZURE_APP_CLIENT_SECRET}
                client-auth-method: client_secret_basic
        soknadsfillager:
            token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            grant-type: client_credentials
            scope: ${SOKNADSFILLAGER_SCOPE}
            authentication:
                client-id: ${AZURE_APP_CLIENT_ID}
                client-secret: ${AZURE_APP_CLIENT_SECRET}
                client-auth-method: client_secret_basic
        soknad-fss-proxy-tokenx:
            well-known-url: ${TOKEN_X_WELL_KNOWN_URL}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
                client-id: ${TOKEN_X_CLIENT_ID}
                client-jwk: ${TOKEN_X_PRIVATE_JWK}
                client-auth-method: private_key_jwt
            token-exchange:
                audience: ${SOKNAD_FSS_PROXY_AUDIENCE}
        digdir-krr-proxy-tokenx:
            well-known-url: ${TOKEN_X_WELL_KNOWN_URL}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
                client-id: ${TOKEN_X_CLIENT_ID}
                client-jwk: ${TOKEN_X_PRIVATE_JWK}
                client-auth-method: private_key_jwt
            token-exchange:
                audience: ${DIGDIR_KRR_PROXY_AUDIENCE}