server:
    servlet:
        context-path: ${SERVLET_CONTEXT_PATH}
management:
    endpoints:
        enabled-by-default: false
        web:
            base-path: /internal
            exposure:
                include: prometheus
            path-mapping:
                prometheus: metrics
    endpoint:
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true
spring:
    datasource:
            url: ${DATASOURCE_URL}
            username: ${DATASOURCE_USERNAME}
            password: ${DATASOURCE_PASSWORD}
            type: oracle.ucp.jdbc.PoolDataSource
            oracleucp:
                min-pool-size: 5
                max-pool-size: 15
    cache:
        ehcache:
            config: ehcache.xml
api-key:
    legacy-sts: ${LEGACY_STS_API_KEY}
    soknad-fss-proxy: ${SOKNAD_FSS_PROXY_API_KEY}
dialogarena:
    navnolink:
        url: ${NAVNO_LINK}
    cms:
        url: ${DIALOGARENA_CMS_URL}
dittnav:
    link:
        url: ${DITTNAV_LINK}
dineutbetalinger:
    link:
        url: ${DINE_UTBETALINGER_LINK}
dkif:
    webservice:
        url: ${DKIF_SERVICE_URL}
dokumentinnsending:
    smtpServer:
        host: ${SMTP_SERVER_HOST}
        port: ${SMTP_SERVER_PORT}
kravdialoginformasjon:
    bilstonad.path: /soknadbilstonad/app
    soknadrefusjondagligreise.path: /soknadrefusjondagligreise/app
    soknadtilleggsstonader.path: /soknadtilleggsstonader/app
    tiltakspenger.path: /soknadtiltakspenger/app
    soknad.aap.gjenopptak.path: /soknadaap/app
    soknad.aap.fortsett.path: /soknadaap/app
    soknad.aap.ordinaer.path: /soknadaap/app
no.nav:
    modig:
        security:
            sts:
                rest:
                    url: ${SECURITY_TOKEN_SERVICE_REST_URL}
                    systemSamlPath: /rest/v1/sts/samltoken
                    exchangePath: /rest/v1/sts/token/exchange
soknad:
    alderspensjon:
        url: ${ALDERSPENSJON_LINK}
    brukerprofil:
        url: ${SOKNAD_BRUKERPROFIL_LINK}
    ettersending:
        antalldager: ${ETTERSENDING_ANTALL_DAGER}
    reelarbeidsoker:
        url: ${REELARBEIDSOKER_LINK}
    skjemaveileder:
        url: ${SKJEMAVEILEDER_LINK}
    webservice:
        arbeid:
            arbeidsforhold:
                url: ${ARBEIDSFORHOLD_SERVICE_URL}
            organisasjon:
                url: ${ORGANISASJON_SERVICE_URL}
        arena:
            maalgruppe:
                url: ${MAALGRUPPEWS_URL}
            personinfo:
                url: ${PERSONINFO_SERVICE_URL}
            sakogaktivitet:
                url: ${SAKOGAKTIVITETWS_URL}
        brukerprofil:
            brukerprofilservice:
                url: ${BRUKER_PROFIL_SERVICE_URL}
        henvendelse:
            informasjonservice:
                url: ${HENVENDELSE_INFORMASJONS_SERVICE_URL}
            fillager:
                url: ${FILLAGER_WS_URL}
            sendsoknadservice:
                url: ${HENVENDELSE_SENDSOKNAD_URL}
        person:
            personservice:
                url: ${PERSON_SERVICE_URL}
soknadinnsending:
    soknad:
        path: /soknadinnsending/soknad
soknadtilleggsstonader:
    path: /soknadtilleggsstonader/app
saksoversikt:
    link:
        url: ${SAKSOVERSIKT_LINK}
sendsoknad:
    datadir: ${SEND_SOKNAD_DATADIR}
    webservice:
        kodeverk:
            url: ${KODEVERK_SERVICE_URL}
systemuser:
    sendsoknad:
        username: ${SERVICEUSER_USERNAME}
        password: ${SERVICEUSER_PASSWORD}
    personInfo:
        username: ${PERSONINFORMASJON_USERNAME}
        password: ${PERSONINFORMASJON_PASSWORD}
no.nav.security.jwt:
    issuers: tokenx,loginservice
    issuer.tokenx:
        discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
        #https://soknad-oauth2-mock.dev.nav.no/default/.well-known/openid-configuration
        accepted_audience: ${ACCEPTED_AUDIENCE}
    issuer.loginservice:
        discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
        accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
        proxyurl: http://webproxy-nais.nav.no:8088
        cookiename: selvbetjening-idtoken
    client.registration:
        azuread:
            token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            grant-type: client_credentials
            scope: ${SOKNAD_FSS_PROXY_SCOPE}
            authentication:
                client-id: ${AZURE_APP_CLIENT_ID}
                client-secret: ${AZURE_APP_CLIENT_SECRET}
                client-auth-method: client_secret_basic
        tokenx:
            well-known-url: ${TOKEN_X_WELL_KNOWN_URL}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
                client-id: ${TOKEN_X_CLIENT_ID}
                client-jwk: ${TOKEN_X_PRIVATE_JWK}
                client-auth-method: private_key_jwt
            token-exchange:
                audience: dev-sbs:team-soknad:soknad-fss-proxy-q1
                
            
