spring:
    datasource:
            url: jdbc:oracle:thin:@d32dbfl003.oera-t.local:1521/sendsoknad_q1
            username: ${DATASOURCE_USERNAME}
            password: ${DATASOURCE_PASSWORD}
            type: oracle.ucp.jdbc.PoolDataSource
            oracleucp:
                min-pool-size: 5
                max-pool-size: 15
soknad:
    alderspensjon:
        url: ${ALDERSPENSJON_LINK}
    brukerprofil:
        url: ${SOKNAD_BRUKERPROFIL_LINK}
    ettersending:
        antalldager: ${ETTERSENDING_ANTALL_DAGER}
    reelarbeidsoker:
        url: ${REELARBEIDSOKER_LINK}
    skjemaveileder:
        url: ${SKJEMAVEILEDER_LINK}
    webservice:
        brukerprofil:
            brukerprofilservice:
                url: ${BRUKER_PROFIL_SERVICE_URL}
        henvendelse:
            sendsoknadservice:
                url: ${HENVENDELSE_SENDSOKNAD_URL}
        person:
            personservice:
                url: ${PERSON_SERVICE_URL}
        arena:
            sakogaktivitet:
                url: ${SAKOGAKTIVITETWS_URL}
            maalgruppe:
                url: ${MAALGRUPPEWS_URL}
soknadinnsending:
    soknad:
        path: /soknadinnsending/soknad
soknadtilleggsstonader:
    path: /soknadtilleggsstonader/app
saksoversikt:
    link:
        url: ${SAKSOVERSIKT_LINK}
sendsoknad:
    datadir: ${SEND_SOKNAD_DATADIR}
    webservice:
        kodeverk:
            url: ${KODEVERK_SERVICE_URL}
dialogarena:
    navnolink:
        url: ${NAVNO_LINK}
    cms:
        url: ${DIALOGARENA_CMS_URL}
dittnav:
    link:
        url: ${DITTNAV_LINK}
dineutbetalinger:
    link:
        url: ${DINE_UTBETALINGER_LINK}
dokumentinnsending:
    smtpServer:
        host: ${SMTP_SERVER_HOST}
        port: ${SMTP_SERVER_PORT}
no.nav:
       modig:
           security:
               sts:
                  url: ${SECURITY_TOKEN_SERVICE_URL}