apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: team-soknad
  labels:
    team: team-soknad
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50M" # Note! Use the same value as VedleggRessurs.MAKS_TOTAL_FILSTORRELSE
spec:
  image: {{image}}
  ingresses:
  {{#each ingress}}
    - "{{this}}"
  {{/each}}
  prometheus:
    enabled: true
    path: {{contextPath}}/internal/metrics
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 512Mi
  replicas:
    min: 4
    max: 6
  kafka:
    pool: {{kafka-pool}}
    streams: true
  tokenx:
    enabled: true
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: soknadbilstonad
        - application: soknadinnsending
        - application: soknadrefusjondagligreise
        - application: soknadtilleggsstonader
        - application: soknadtiltakspenger
        - application: statuspoll
          namespace: navdig
    outbound:
      external:
        - host: soknad-fss-proxy.prod-fss-pub.nais.io
        - host: soknad-fss-proxy.prod.nav.no
        - host: tjenester.nav.no
        - host: soknadsmottaker-gcp.intern.nav.no
        - host: soknadsfillager-gcp.intern.nav.no
        - host: api-gw.oera.no
        - host: a30dbfl005.oera.no
          ports:
            - port: 1521
        - host: www.nav.no

  envFrom:
    - secret: sendsoknad-google-secret
  env:
    - name: ALDERSPENSJON_LINK
      value: https://tjenester.nav.no/pselv/skjema/alderspensjon.jsf
    - name: ARBEIDSFORHOLD_SERVICE_URL
      value: {{ soknad-fss-proxy }}/aareg-services/ArbeidsforholdService/v3
    - name: ACCEPTED_AUDIENCE
      value: {{ accepted-audience }}
    - name: BRUKERNOTIFIKASJON_TJENSTE_URL
      value: "https://tjenester.nav.no"
    - name: BRUKER_PROFIL_SERVICE_URL
      value: {{ soknad-fss-proxy }}/tpsws-aura/ws/Brukerprofil/v1
    - name: DITTNAV_LINK
      value: https://www.nav.no/minside
    - name: DIALOGARENA_CMS_URL
      value: https://appres.nav.no
    - name: DINE_UTBETALINGER_LINK
      value: https://tjenester.nav.no/utbetalingsoversikt/
    - name: DIGDIR_KRR_PROXY_URL
      value: https://digdir-krr-proxy.intern.nav.no
    - name: DIGDIR_KRR_PROXY_PING
      value: /internal/health/readiness
    - name: DIGDIR_KRR_PROXY_AUDIENCE
      value: prod-gcp:team-rocket:digdir-krr-proxy
    - name: ETTERSENDING_ANTALL_DAGER
      value: "70"
    - name: KODEVERK_SERVICE_URL
      value: {{ soknad-fss-proxy }}/ws/kodeverk/v2
    - name: KODEVERK_REST_URL
      value: https://kodeverk-api.nav.no
    - name: MAALGRUPPEWS_URL
      value: {{ soknad-fss-proxy }}/ail_ws/maalgruppe_v1
    - name: NAVNO_LINK
      value: https://www.nav.no
    - name: ORGANISASJON_SERVICE_URL
      value: {{ soknad-fss-proxy }}/ereg/ws/OrganisasjonService/v4
    - name: PERSON_SERVICE_URL
      value: {{ soknad-fss-proxy }}/tpsws-aura/ws/Person/v1
    - name: PERSONINFO_SERVICE_URL
      value: {{ soknad-fss-proxy }}/arena_ws/services/PersonInfoService
    - name: REELARBEIDSOKER_LINK
      value: https://arbeidssokerregistrering.nav.no/start?fraAap=true
    - name: SAKSOVERSIKT_LINK
      value: https://person.nav.no/mine-saker
    - name: SAKOGAKTIVITETWS_URL
      value: {{ soknad-fss-proxy }}/ail_ws/SakOgAktivitet_v1
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw.oera.no/legacy-sts
    - name: SEND_SOKNAD_DATADIR
      value: /data/sendsoknad
    - name: SKJEMAVEILEDER_LINK
      value: https://www.nav.no/soknader
    - name: SMTP_SERVER_HOST
      value: smtp.adeo.no
    - name: SMTP_SERVER_PORT
      value: "25"
    - name: SOKNAD_BRUKERPROFIL_LINK
      value: https://tjenester.nav.no/brukerprofil/
    - name: SOKNADSMOTTAKER_HOST
      value: https://soknadsmottaker-gcp.intern.nav.no
    - name: SOKNADSFILLAGER_HOST
      value: https://soknadsfillager-gcp.intern.nav.no
    - name: SERVLET_CONTEXT_PATH
      value: {{contextPath}}
    - name: SOKNAD_FSS_PROXY_SCOPE
      # See https://doc.nais.io/security/auth/azure-ad/concepts/#default-scope
      value: api://prod-fss.team-soknad.soknad-fss-proxy/.default
    - name: SOKNAD_FSS_PROXY_AUDIENCE
      value: prod-fss:team-soknad:soknad-fss-proxy
    - name: SOKNADSMOTTAKER_SCOPE
      value: api://prod-gcp.team-soknad.soknadsmottaker/.default
    - name: SOKNADSFILLAGER_SCOPE
      value: api://prod-gcp.team-soknad.soknadsfillager/.default
    - name: KAFKA_SECURITY
      value: "TRUE"
    - name: KAFKA_MESSAGE_TOPIC
      value: "team-soknad.privat-soknadinnsending-messages-v2"
    - name: SOKNADINNSENDING_URL
      value: "https://tjenester.nav.no/soknadinnsending/backend"