name: Build, push, and deploy

on:
    push:
        branches:
            - 'main'
            - 'q0-pipeline'
            - 'q1-pipeline'
            - 'sendsoknad-auth'
        paths-ignore:
            - '**.md'
            - '**/**.md'
    pull_request:
        branches:
            - 'main'
        paths-ignore:
            - '**.md'
            - '**/**.md'
            - '.github/workflows/main.yml'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/sendsoknad-boot:${{ github.sha }}

jobs:

  build-and-push:
    name: Build and push Docker container
    if: github.ref == 'refs/heads/q0-pipeline' || github.ref == 'refs/heads/q1-pipeline' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/sendsoknad-auth'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
          java-version: '11.x'
    - name: set timezone
      uses: szenius/set-timezone@v1.0
      with:
          timezoneLinux: "Europe/Oslo"
    - name: Build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B package --file pom.xml
    - name: Build and publish Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker build --tag ${IMAGE} .
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${IMAGE}
  deploy-q0:
    name: Deploy to team namespace (NAIS) as Q0
    needs: build-and-push
    if: github.ref == 'refs/heads/q0-pipeline'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-sbs
        RESOURCE: nais/nais-q0.yml
  deploy-q1:
    name: Deploy to team namespace (NAIS) as Q1
    needs: build-and-push
    if: github.ref == 'refs/heads/q1-pipeline'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-sbs
        RESOURCE: nais/nais-q1.yml
  deploy-auth:
    name: Deploy poc setup of tokenx
    needs: build-and-push
    if: github.ref == 'refs/heads/sendsoknad-auth'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-sbs
        RESOURCE: nais/nais-auth.yml
  deploy-prod:
    name: Deploy to prod 
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-sbs
        RESOURCE: nais/nais.yml
   