name: Build, push, and deploy

on:
    push:
        branches-ignore:
            - 'preprod'
            - 'preprod-alt'
            - 'main'
        paths-ignore:
            - '**.md'
            - '**/**.md'
            - 'docs/Pictures/**.png'

env:
  docker_image: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-push:
    name: Build feature branches

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: set timezone
        uses: szenius/set-timezone@v1.2
        with:
            timezoneLinux: "Europe/Oslo"
      - name: Build
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B package --file pom.xml
      - name: Build Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${docker_image} .
