name: Build, push, and deploy
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**/**.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**/**.md'
      - '.github/workflows/**.yml'
      - 'docs/**'

jobs:
  build-and-push:
    permissions:
      contents: "read"
      id-token: "write"
    name: Build and push Docker container
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: set timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Oslo"
      - name: Build with maven
        run: mvn install --file pom.xml

      - name: Dependency submission (for dependabot)
        uses: advanced-security/maven-dependency-submission-action@v3

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
            team: team-soknad
            identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
            project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
            image_suffix: prod
            byosbom: target/bom.json
    outputs:
        image: ${{ steps.docker-build-push.outputs.image }}

  deploy-sendsoknad-prod:
    name: Deploy to prod
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais-prod.yml
          VARS: nais/sendsoknad.json
          VAR: image=${{needs.build-and-push.outputs.image}}

  deploy-alerts-prod:
    needs: deploy-sendsoknad-prod
    name: Deploy alerts to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/alerts.yml
          VARS: nais/prod-alert.json

