# This workflow can be used to manually trigger a build and deploy of any branch using a workflow_dispatch event.
name: Deploy to preprod-alt

on:
  workflow_dispatch:

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/sendsoknad-boot:${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
          java-version: '11.x'
    - name: set timezone
      uses: szenius/set-timezone@v1.0
      with:
          timezoneLinux: "Europe/Oslo"
    - name: Build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B package -DskipTests --file pom.xml
    - name: Build and publish Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker build --tag ${IMAGE} .
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${IMAGE}
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: nais/preprod-sbs/nais-preprod.yml
          VARS: nais/preprod-sbs/sendsoknad-alt.json
